apiVersion: v1
kind: Service
metadata:
  name: fastapi-app
spec:
  type: LoadBalancer  # Use NodePort or ClusterIP for internal access only
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: fastapi-app
