apiVersion: v1
kind: Service
metadata:
  name: fastapi-app
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080  # Optional: Specify a node port in the range 30000-32767; if not specified, one will be allocated automatically
  selector:
    app: fastapi-app
